apiVersion: v2
name: urlaubsverwaltung
description: Die Urlaubsverwaltung ist eine Web-Anwendung, die es ermöglicht, Urlaubsanträge von Mitarbeitern elektronisch zu verwalten.
type: application
version: 5.0.0
appVersion: 5.0.0-M3
keywords:
  - urlaub
home: https://github.com/urlaubsverwaltung/urlaubsverwaltung
sources:
  - https://github.com/urlaubsverwaltung/urlaubsverwaltung
maintainers:
  - name: Johannes Graf
    email: Johannes.Graf@focus-shift.de
  - name: Tobias Schneider
    email: Tobias.Schneider@focus-shift.de
dependencies:
  - name: postgresql
    version: 12.12.10
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
