version: '3.9'
services:

  urlaubsverwaltung:
    image: urlaubsverwaltung/urlaubsverwaltung:5.0.0-RC1
    network_mode: "host"
    restart: always
    environment:
      SERVER_PORT: 8080
      # Database
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5434/urlaubsverwaltung
      SPRING_DATASOURCE_USERNAME: urlaubsverwaltung
      SPRING_DATASOURCE_PASSWORD: urlaubsverwaltung
      # Mail
      UV_MAIL_FROM: urlaubsverwaltung@example.org
      UV_MAIL_FROMDISPLAYNAME: urlaubsverwaltung
      UV_MAIL_REPLYTO: urlaubsverwaltung@example.org
      UV_MAIL_REPLYTODISPLAYNAME: urlaubsverwaltung
      UV_MAIL_APPLICATIONURL: http://localhost:8080
      SPRING_MAIL_HOST: localhost
      SPRING_MAIL_PORT: 1025
      # Calendar
      UV_CALENDAR_ORGANIZER: organizer@example.org
      # OpenID Connect identity provider
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DEFAULT_CLIENT-ID: urlaubsverwaltung
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DEFAULT_CLIENT-SECRET: urlaubsverwaltung-secret
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DEFAULT_CLIENT-NAME: urlaubsverwaltung
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DEFAULT_PROVIDER: default
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DEFAULT_SCOPE: openid,profile,email,roles
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DEFAULT_AUTHORIZATION-GRANT-TYPE: authorization_code
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DEFAULT_REDIRECT-URI: http://localhost:8080/login/oauth2/code/{registrationId}
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_DEFAULT_ISSUER-URI: http://localhost:8090/realms/urlaubsverwaltung
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI: http://keycloak:8090/realms/urlaubsverwaltung
    depends_on:
      keycloak:
        condition: service_started
      postgres:
        condition: service_healthy
      mailhog:
        condition: service_started

  postgres:
    image: postgres:15.3
    environment:
      POSTGRES_DB: urlaubsverwaltung
      POSTGRES_USER: urlaubsverwaltung
      POSTGRES_PASSWORD: urlaubsverwaltung
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 3s
      timeout: 1s
      retries: 5

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - '1025:1025'
      - '8025:8025'

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.4
    command: [ "start-dev", "--import-realm" ]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8090
      KC_HOSTNAME_STRICT: 'false'
      KC_HOSTNAME_STRICT_HTTPS: 'false'
      KC_HEALTH_ENABLED: 'true'
      KC_CACHE: 'local'
    ports:
      - '8090:8090'
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import
