apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "urlaubsverwaltung.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "urlaubsverwaltung.name" . }}
    helm.sh/chart: {{ include "urlaubsverwaltung.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  application.properties: |-
    # Deactivate mail health check to prevent k8s to crashLoop,
    # because mail will be configured after the first mail was sent.
    # see https://github.com/synyx/urlaubsverwaltung/issues/507
    management.health.mail.enabled=false
    # log everything to stdout
    logging.file.name=
    {{- if .Values.applicationProperties }}
    {{ .Values.applicationProperties | indent 4 }}
    {{- end -}}
