version: '3.9'
services:
  mariadb:
    image: mariadb:10.6.11
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'urlaubsverwaltung'
      MYSQL_USER: 'urlaubsverwaltung'
      MYSQL_PASSWORD: 'urlaubsverwaltung'
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - '3306:3306'
    healthcheck:
      test: ["CMD", "bash", "-c", "/usr/bin/mysql --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD --execute \"SHOW DATABASES;\""]
      interval: 3s
      timeout: 1s
      retries: 5

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - '1025:1025'
      - '8025:8025'

  app:
    image: synyx/urlaubsverwaltung:4.41.0-SNAPSHOT
    expose:
      - "8080"
    environment:
      UV_SECURITY_AUTH: 'default'
      UV_ACCOUNT_UPDATE_CRON: "*/10 * * * * *"
      SPRING_PROFILES_ACTIVE: 'demodata'
      SPRING_DATASOURCE_URL: 'jdbc:mariadb://mariadb/urlaubsverwaltung'
      SPRING_DATASOURCE_USERNAME: 'urlaubsverwaltung'
      SPRING_DATASOURCE_PASSWORD: 'urlaubsverwaltung'
      SPRING_MAIL_HOST: 'mailhog'
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 30s
      retries: 5

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "80:80"

volumes:
  mariadb_data: {}
