name: Mark issue as planned

on:
  issues:
    types: [ milestoned ]

jobs:
  apply-label:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/github-script@v4
        name: Add label 'status planned' to issue when milestoned
        with:
          github-token: ${{github.token}}
          script: |
            github.issues.addLabels({
              ...context.repo,
              issue_number: context.issue.number,
              labels: ['status: planned']
            })
            .catch(e => { console.log(e.message) })
      - uses: actions/github-script@v4
        name: Remove label 'status new' to issue when milestoned
        with:
          github-token: ${{github.token}}
          script: |
            github.issues.removeLabel({
              ...context.repo,
              issue_number: context.issue.number,
              name: 'status: new'
            })
            .catch(e => { console.log(e.message) })
