name: Urlaubsverwaltung CI

on: [push]

jobs:
  build:
    name: build with jdk ${{ matrix.java }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11', '12', '13' ]
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: ./mvnw --batch-mode clean verify

  dependency-check:
    name: analyse with owasp dependency check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run OWASP dependency check
        run: >
          ./mvnw --batch-mode clean
          org.owasp:dependency-check-maven:check
      - uses: actions/upload-artifact@v1
        with:
          name: dependency-check-report
          path: target/dependency-check-report.html

  sonar:
    name: analyse with sonarqube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}-sonarqube
          restore-keys: |
            ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}-sonarqube
            ${{ runner.os }}-maven-
      - name: Maven clean
        run: ./mvnw clean
      - name: Run SonarCloud analyse
        run: >
          ./mvnw --batch-mode
          org.jacoco:jacoco-maven-plugin:prepare-agent
          verify
          org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=synyx
          -Dsonar.projectKey=org.synyx:urlaubsverwaltung
          -Dsonar.javascript.lcov.reportPaths=target/js-coverage/lcov.info
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
