name: Urlaubsverwaltung CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  compile:
    name: compile with jdk ${{ matrix.java }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11', '14' ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Compile
        run: ./mvnw --batch-mode clean compile
  build:
    name: build with jdk 11
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: ./mvnw --batch-mode clean verify
      - name: Build docker image and push
        if: github.ref == 'refs/heads/master'
        run: >
          ./mvnw --batch-mode
          docker:build
          docker:push
          -Ddocker.name=synyx/urlaubsverwaltung/urlaubsverwaltung
          -Ddocker.push.registry=docker.pkg.github.com
          -Ddocker.push.username=${{ github.actor }}
          -Ddocker.push.password=${{ secrets.GITHUB_TOKEN }}
          -Ddocker.pull.username=${{ secrets.DOCKER_USERNAME }}
          -Ddocker.pull.password=${{ secrets.DOCKER_PASSWORD }}

  sonar:
    name: analyse with sonarqube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}-sonarqube
          restore-keys: |
            ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}-sonarqube
            ${{ runner.os }}-maven-
      - name: Maven clean
        run: ./mvnw clean
      - name: Run SonarCloud analyse
        run: >
          ./mvnw --batch-mode
          -Pcoverage
          verify
          sonar:sonar
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=synyx
          -Dsonar.projectKey=org.synyx:urlaubsverwaltung
          -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml,target/site/jacoco-it/jacoco.xml
          -Dsonar.javascript.lcov.reportPaths=target/js-coverage/lcov.info
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
